create table if not exists public.session_metrics (
  id bigint generated by default as identity primary key,
  user_id text not null,
  session_id text not null,
  scenario_id text not null,
  overall_score integer not null check (overall_score between 0 and 100),
  duration_sec integer not null check (duration_sec >= 0),
  attempts integer not null default 1,
  app_version text not null,
  timestamp timestamptz not null default now()
);

create index if not exists idx_session_metrics_user_ts
  on public.session_metrics (user_id, timestamp desc);

create index if not exists idx_session_metrics_scenario_ts
  on public.session_metrics (scenario_id, timestamp desc);
